### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by kidd001** [uetchy/wercker-step-gh-pages#2]
Hi there,

I'm amazed by the way how Wercher deploys post to prod, so I give it a try but I got struck by a weird issue, would like some advice from you to get it solved.

So I follow every single step in your tutorial and get Wercker properly (I assume) for my project, below is how the logs show:

![image](https://cloud.githubusercontent.com/assets/2474906/10710368/0ef11d54-7ab4-11e5-957f-0dfa645b6b68.png)

But when I try to open up my Github Page (http://kidd001.github.io), there's nothing comes up, does it mean "public" folder doesn't get created by Wercker?

Cheers,
Kexin`

**Comment by uetchy** [comment]
You should set up deploy section of wercker.yml like this:

``` yaml
~chomp~
build:
  #blahblahblah
deploy:
  steps:
    - uetchy/gh-pages:
        token: $GITHUB_TOKEN
        repo: randompaper/randompaper.github.io
        path: public
        domain: randompaper.co
```

Particularly, you must replace [that](https://github.com/kidd001/kidd001.github.io/blob/gh-pages/wercker.yml#L14) with `path: build` because of changing parameters.
